# -*- coding: utf-8 -*-
"""Computational Exercise 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OKvM6pkT3jqrTtgIIUUNJUQUqSBM0on8
"""

import numpy as np; import matplotlib.pyplot as plt; import pandas as pd; import cmath; import math; import sys; plt.rcParams['figure.figsize']= [15,6]

my_file = open("NewHunt_21D070021.dat", "r")
  
data = my_file.read()
  
data_into_list = data.split("\n")
#print(data_into_list)
my_file.close()

complex_num_list = []

for i in range(0,len(data_into_list)-1):
  complex_num_list.append(complex(data_into_list[i]))

real_values = []
imag_values = []
mod_values = []
indices = []

for i in range(0,len(complex_num_list)):
  real_values.append(complex_num_list[i].real)
  imag_values.append(complex_num_list[i].imag)
  mod_values.append(math.sqrt(real_values[i]**2+imag_values[i]**2))
  indices.append(i)

#for i in range(0,len(real_values)):
  #min_index = i
  #for j in range(i+1, len(real_values)):
    #if real_values[min_index] > real_values[j]:
       #min_index = j
               
  #real_values[i], real_values[min_index] = real_values[min_index], real_values[i]
  #imag_values[i], imag_values[min_index] = imag_values[min_index], imag_values[i]
  #mod_values[i], mod_values[min_index] = mod_values[min_index], mod_values[i]

plt.scatter(indices, real_values, s=20)  #blue 
plt.scatter(indices, imag_values, s=20)  #orange